"""add file search columns to session

Revision ID: fe9dce86cd52
Revises: 38c9ee921d84
Create Date: 2025-12-23 18:24:06.443664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe9dce86cd52'
down_revision: Union[str, Sequence[str], None] = '38c9ee921d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure enum chatmode contains FILE_SEARCH before inserts
    op.execute("ALTER TYPE chatmode ADD VALUE IF NOT EXISTS 'FILE_SEARCH'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('file_search_store_name', sa.String(length=255), nullable=True))
    op.add_column('session', sa.Column('file_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'file_name')
    op.drop_column('session', 'file_search_store_name')
    # ### end Alembic commands ###
